name: Deploy SimpleTimeService

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      tf_action:
        description: "Terraform action to perform"
        required: true
        type: choice
        options:
          - apply
          - destroy
      image_tag:
        description: "Optional Docker image tag (defaults to commit SHA)"
        required: false
      deploy_backend:
        description: 'Deploy backend infrastructure'
        required: true
        default: true
        type: boolean
      deploy_app:
        description: 'Build and push Docker image'
        required: true
        default: true
        type: boolean

jobs:
  docker-build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || 
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_app == 'true' && github.event.inputs.action == 'apply')

    outputs:
      image: ${{ steps.docker.outputs.image }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        id: docker
        run: |
          TAG="${{ inputs.image_tag || github.sha }}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:${TAG}"

          docker build -t "$IMAGE" ./app

          docker push "$IMAGE"

  terraform:
    runs-on: ubuntu-latest
    needs: docker-build-and-push

    defaults:
      run:
        working-directory: terraform/aws

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_ACTION: ${{ inputs.tf_action }}
      TF_VAR_image: ${{ needs.docker-build-and-push.outputs.image }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.0"

      - name: Generate terraform.tfvars for backend
        run: |
          echo "Replacing backend placeholders in provider.tf..."
          
          # Replace placeholders with actual values using sed
          sed -i "s|BACKEND_BUCKET_NAME|${{ secrets.TF_VAR_BUCKET_NAME  }}|g" provider.tf
          sed -i "s|BACKEND_REGION|${{ secrets.AWS_REGION }}|g" provider.tf
          sed -i "s|BACKEND_DYNAMODB_TABLE|${{ secrets.TF_VAR_LOCK_TABLE_NAME }}|g" provider.tf
          
          echo "Updated provider.tf:"
          cat provider.tf

          cat > terraform.tfvars << EOF
          aws_region      = "${{ secrets.AWS_REGION }}"
          tags = {
            Org         = "${{ secrets.ORG }}"
            ManagedBy   = "Terraform"
            Environment = "${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}"
          }
          project_name = "${{ secrets.TF_VAR_PROJECT_NAME }}"
          vpc_cidr = "${{ secrets.TF_VAR_vpc_cidr }}"
          container_image = "${{ env.TF_VAR_image }}"
          container_port = 8000
          task_cpu = 256
          task_memory = 512
          desired_count = 2
          health_check_path = "/"
          EOF
          echo "Generated terraform.tfvars:"
          cat terraform.tfvars

      - name: Terraform init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event.inputs.tf_action != 'destroy'
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.tf_action != 'destroy'
        run: terraform apply -auto-approve tfplan
      
      - name: Terraform Destroy
        if: github.event.inputs.tf_action == 'destroy'
        run: terraform apply -auto-approve tfplan
